Problem 1: Controls AGI code (AT1G01040) in the file LocusGene.tsv and Germplasm.tsv. 
 I check that the AGI code is present in both files and take the first column of both to compare if the values are the same or differ.

To check if the AGI codes are the same in both files or they differ.

In [33]:
#cat LocusGene.tsv  to check the data looks like. As it is tab-separated values, the first column correspond to the AGI code.
locusfile = open("LocusGene.tsv", "r")
LocusGene1_first_value = []  # you make a list with the values for the first column  (AGI code)
for line in locusfile.readlines():  #read from left to right and remove the 
    LocusGene1, Gene, Proteinlength = line.split('\t')   #split() method returns a list of strings after breaking the given string by the specified separator
    LocusGene1_first_value.append(LocusGene1)
    #print(LocusGene1)
    
Germplasm_first_value = []  #the same for the second file and you take the column called Locusplasm2
Germfile = open("Germplasm.tsv", "r") 
for line in Germfile.readlines():
    Locusplasm2, Gene, Phenotype, pubmed = line.split('\t')
    Germplasm_first_value.append(Locusplasm2)
    #print(Locusplasm2)
# Make a conditional to know if the locus differs in length. 
if len(LocusGene1_first_value) != len(Germplasm_first_value):     
    print('The number of rows in file LocusGene.tsv is different from the number of rows in the file Germplasm.csv.')
# I the lenght is the same then, we compare both values to see if the locus is the same and we print Same or Different Locus.
for i in range(len(LocusGene1_first_value)):
    if  LocusGene1_first_value[i]==Germplasm_first_value[i]:
        print("Same Locus: ", LocusGene1_first_value[i], Germplasm_first_value[i])
    else:
        print("Different Locus:", LocusGene1_first_value[i], Germplasm_first_value[i])
    
#Close both files
locusfile.close()
Germfile.close()

Same Locus:  Locus Locus
Same Locus:  AT1G01040 AT1G01040
Same Locus:  AT1G01060 AT1G01060
Same Locus:  AT1G01140 AT1G01140
Same Locus:  AT1G01220 AT1G01220
Same Locus:  AT2G03720 AT2G03720
Same Locus:  AT2G03800 AT2G03800
Same Locus:  AT2G04240 AT2G04240
Same Locus:  AT2G05210 AT2G05210
Same Locus:  AT3G02130 AT3G02130
Same Locus:  AT3G02140 AT3G02140
Same Locus:  AT3G02230 AT3G02230
Same Locus:  AT3G02260 AT3G02260
Same Locus:  AT3G02310 AT3G02310
Same Locus:  AT3G02680 AT3G02680
Same Locus:  AT3G02850 AT3G02850
Same Locus:  AT3G02870 AT3G02870
Same Locus:  AT3G03260 AT3G03260
Same Locus:  AT4G14790 AT4G14790
Same Locus:  AT4G15210 AT4G15210
Same Locus:  AT4G15560 AT4G15560
Same Locus:  AT4G15570 AT4G15570
Same Locus:  AT4G15802 AT4G15802
Same Locus:  AT4G15880 AT4G15880
Same Locus:  AT4G16420 AT4G16420
Same Locus:  AT4G16480 AT4G16480
Same Locus:  AT5G10480 AT5G10480
Same Locus:  AT5G10510 AT5G10510
Same Locus:  AT5G11110 AT5G11110
Same Locus:  AT5G11260 AT5G11260
Same Locus:  AT5G11510 AT5G11510
Same Locus:  AT5G12200 AT5G12200
Same Locus:  AT5G13290 AT5G13290

Problem 2: Design and create the database.

2) I Create the database called "Exam2db"
2) Table 1 with columns (Locus, Gene, and ProteinLength) for LocusGene.tsv
3) Table 2 with 1:1 relationship (locus, germplasm, phenotype and pubmed) for Germplasm.tsv

In [1]:
# To start mysql with the SqLMagic and connect.
%load_ext sql
%config SqlMagic.autocommit=False
%sql mysql+pymysql://root:root@127.0.0.1:3306/mysql

'Connected: root@mysql'

In [28]:
#In case I need to remove or drop the table
#%sql drop database Exam2db;
#Sow databases to see what is inside, before the creation of the database

%sql show databases;

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
7 rows affected.

[('information_schema',),
 ('Exam2db',),
 ('germplasm',),
 ('mysql',),
 ('performance_schema',),
 ('sys',),
 ('testing123',)]

In [10]:
#To create the database called "Exam2db" and show it
%sql create database Exam2db;
%sql show databases;
#Table 1 LocusGene with columns (Locus, Gene, and ProteinLength) and values type (VARCHAR (10) since the AGI code has 9 characters ,VARCHAR (10) since the gene usually has less than 10 characters AND INTERGER since the length is a number) for LocusGene.tsv
#As the Locus gene is common for both data files (Germplasm and LocusGene) I will use it as primary Key.
%sql use Exam2db;
%sql CREATE TABLE LocusGene(Locus VARCHAR(10) PRIMARY KEY, Gene VARCHAR(10) NOT NULL, ProteinLength INTEGER NOT NULL);
%sql DESCRIBE LocusGene;

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
(pymysql.err.ProgrammingError) (1007, "Can't create database 'Exam2db'; database exists")
[SQL: create database Exam2db;]
(Background on this error at: http://sqlalche.me/e/f405)
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
7 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
0 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql

InternalError: (pymysql.err.InternalError) (1050, "Table 'LocusGene' already exists")
[SQL: CREATE TABLE LocusGene(Locus VARCHAR(10) PRIMARY KEY, Gene VARCHAR(10) NOT NULL, ProteinLength INTEGER NOT NULL);]
(Background on this error at: http://sqlalche.me/e/2j85)

In [4]:
#Table 2 LocusGene with columns (Locus, Germplasm, Phenotype and pubmed) and values type (VARCHAR(10) for the locus which si the primary key, VARCHAR(50),VARCHAR(600)a nd the INTEGER which is the pubmed number)
%sql use Exam2db;  #use the database
%sql CREATE TABLE Germplasm(Locus VARCHAR(10) PRIMARY KEY, Germplasm VARCHAR(50) NOT NULL, Phenotype VARCHAR(600) NOT NULL, pubmed INTEGER NOT NULL);
%sql DESCRIBE Germplasm;  # to show the structure of a table

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
0 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
0 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
4 rows affected.

[('Locus', 'varchar(10)', 'NO', 'PRI', None, ''),
 ('Germplasm', 'varchar(50)', 'NO', '', None, ''),
 ('Phenotype', 'varchar(600)', 'NO', '', None, ''),
 ('pubmed', 'int(11)', 'NO', '', None, '')]

As  we have check it before, each row in both table is equivalent to the other one in the table, for this reason the id or the PRIMARY KEY for both is the Locus. This is the relation 1:1 to join te tables with the command SELECT * FROM

In [34]:
#This is use to make the relationship since the Locus of both tables is the same, we use them as the ID or te KEY
%sql SELECT * FROM Germplasm, LocusGene WHERE Germplasm.Locus=LocusGene.Locus

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
32 rows affected.

[('AT1G01040', 'CS3828', 'Increased abundance of miRNA precursors.', 17369351, 'AT1G01040', 'DCL1', 332),
 ('AT1G01060', 'lhy-101', 'The mutant plants are hypersensitive to both FRc and Rc light treatments in hypocotyl elongation and exhibits a small reciprocal enlargement in cotyledon area, albeit not statistically significant.', 16891401, 'AT1G01060', 'LHY', 290),
 ('AT1G01140', 'SALK_058629', 'hypersensitive to low potassium media', 17486125, 'AT1G01140', 'CIPK9', 223),
 ('AT1G01220', 'SALK_012400C', 'fkgp-1 mutants have about 40 times more L-fucose than wild type Arabidopsis plants, but the levels of other monosaccharides do not appear to differ s ... (41 characters truncated) ... henotypic abnormalities were observed in the fkgp-1 mutants, nor were any differences in the sugar composition of cell wall polysaccharides detected.', 18199744, 'AT1G01220', 'FKGP', 190),
 ('AT2G03720', 'SALK_042433', 'Multiple straight hairs', 16367956, 'AT2G03720', 'MRH6', 189),
 ('AT2G03800', 'gek1-1', 'Ethanol hypersensitivity.', 15215505, 'AT2G03800', 'GEK1', 196),
 ('AT2G04240', 'xerico', 'Resistant to exogenous ABA. Seeds contained lower amounts of endogenous ABA than wildtype.', 17933900, 'AT2G04240', 'XERICO', 256),
 ('AT2G05210', 'pot1-1', 'No visible phenotype.', 17627276, 'AT2G05210', 'POT1A', 221),
 ('AT3G02130', 'rpk2-2', 'The homozygous progeny is indistinguishable from wild-type plants during vegetative growth but showed several morphological alterations after bolting. These plants displayed enhanced inflorescence branching and formed three times as many siliques and flowers as did wild-type plants.', 17419837, 'AT3G02130', 'RPK2', 284),
 ('AT3G02140', 'afp4-1', 'Decreased germination on high concentrations of glucose and sorbitol.', 18484180, 'AT3G02140', 'TMAC2', 300),
 ('AT3G02230', 'rgp1-1', 'rgp1-1 mutants have significantly lower levels of UDP-L-arabinose mutase activity compared to wild-type plants and significantly lower levels of arabinose in their cell walls.', 21478444, 'AT3G02230', 'RGP1', 301),
 ('AT3G02260', 'tir3-1 RGLG1:rglg1 rglg2', 'The triple homozygous progeny has low viability, accumulated anthocyanin, and all plants died before shoot emergence.', 17586653, 'AT3G02260', 'BIG', 279),
 ('AT3G02310', 'sep2-1', 'Non-described subtle phenotype.', 10821278, 'AT3G02310', 'SEP2', 175),
 ('AT3G02680', 'atnbs1-1', 'Significantly smaller when grown in the presence of methyl methanosulfonate (MMS) with root growth.  Normal growth under standard growth conditions.', 17672843, 'AT3G02680', 'NBS1', 190),
 ('AT3G02850', 'CS3816', 'The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion.', 17568770, 'AT3G02850', 'SKOR', 234),
 ('AT3G02870', 'vtc4-1', 'ascorbate deficient', 16595667, 'AT3G02870', 'VTC4', 311),
 ('AT3G03260', 'hdg8-1', 'No visible phenotype.', 16778018, 'AT3G03260', 'HDG8', 194),
 ('AT4G14790', 'pdd17', 'Defective pollen development.', 19237690, 'AT4G14790', 'SUV3', 312),
 ('AT4G15210', 'bmy1-2', 'Plants cold-shocked for 6h have an increased starch content compared to wildtype.', 16297066, 'AT4G15210', 'BAM5', 313),
 ('AT4G15560', 'cla1-1', 'Mutant seeds grown on medium supplemented with non-phosphorylated synthetic 1-deoxy-D-xylulose (DX) develop green leaves.', 10982425, 'AT4G15560', 'DXS', 219),
 ('AT4G15570', 'maa3', 'Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT.', 18772186, 'AT4G15570', 'MAA3', 294),
 ('AT4G15802', 'Athspb-2', 'Early flowering, reduced fertility, aborted seeds.', 20388662, 'AT4G15802', 'HSBP', 254),
 ('AT4G15880', 'esd4-2', 'Decreased mRNA levels of the floral repressors FLC and MAF4 and increased mRNA levels of the floral activators FT and SOC1.', 17513499, 'AT4G15880', 'ESD4', 265),
 ('AT4G16420', 'prz1-1', 'Altered response to auxin and cytokinin', 12747832, 'AT4G16420', 'ADA2B', 279),
 ('AT4G16480', 'atint4-2', 'No visible phenotype.', 16603666, 'AT4G16480', 'INT4', 284),
 ('AT5G10480', 'pas2-3', 'Segregates 25% embryo lethal.', 18799749, 'AT5G10480', 'PAS2', 301),
 ('AT5G10510', 'plt3-1', 'Short roots and shortened root meristem.', 17960244, 'AT5G10510', 'AIL6', 310),
 ('AT5G11110', 'kns2', 'Defects are specific to pollen exine structure. Smaller mesh size in the exine structure. Increased number of baculae. Fully fertile.', 18779216, 'AT5G11110', 'SPS2', 232),
 ('AT5G11260', 'hy5-101', 'Under FRc conditions, the length mutant hypocotyls is increased compared to that of wild-type plants.  Under Rc conditions, the hypocotyl length is also increased and the cotyledon area is smaller.', 16891401, 'AT5G11260', 'HY5', 221),
 ('AT5G11510', 'myb3r4-1', 'No visible phenotype.', 17287251, 'AT5G11510', 'MYB3R-4', 336),
 ('AT5G12200', 'pyd2-2', 'The pyd2-2 mutant has a wild-type appearance under normal growth conditions. Pyrimidine nucleotide and uridine levels are not changed in the mutant, but uracil levels are increased. These mutants cannot grow normally when uracil is provided as a sole nitrogen source.', 19413687, 'AT5G12200', 'PYD2', 310),
 ('AT5G13290', 'crn-1', 'Increased meristem size. Vegetative meristems are are 30% larger than wild type. After bolting inflorescence meristems are enlarged and occasionally fasciated. Flowers occasionally produce extra organs in the first 3.', 12345678, 'AT5G13290', 'CRN', 189)]

Problem 3 : Fill the database. To fill the database I am importing the information from the .TSV files,

In [23]:
#I first connect mysql to the database db=Exam2db
import pymysql.cursors
connection = pymysql.connect(host='localhost',
                            user='root',
                            password='root',
                            db='Exam2db',   # the name of the database we use
                            charset='utf8mb4', # it is important for unusual characters!
                            cursorclass=pymysql.cursors.DictCursor)
                           
#I open both files to read them    
Germfile = open("Germplasm.tsv", "r")
Germfile.seek(0)
Germfile = Germfile.readlines()
Locusfile = open("LocusGene.tsv", "r") 
Locusfile.seek(0) 
Locusfile = Locusfile.readlines()
# I read all the files row by row and split them removing the tabs, since the file is separated by tabs. I assign to index of the row the name of a variable (namelocus,namegerm, namephen,namepub) 
try:
    with connection.cursor() as cursor:
        for data in range (1, len(Germfile)):
            row = Germfile[data].split ('\t')
            namelocus = row[0]
            namegerm = row[1]
            namephen= row[2]
            namepub= row[3]
 #  I will insert the data using sql into the table Germplasm and I use string (%s)and  digit (%d) format     
            tablevariables = (namelocus,namegerm, namephen,namepub)
            sql = "INSERT INTO Germplasm (Locus, Germplasm, Phenotype, pubmed) VALUES (%s, %s, %s, %s)"
            try:
                cursor.execute (sql,tablevariables)
            except:
                print('Warning, the entry ' + namelocus + ' is already in mysql.')
#  I use the try and except to do not create a duplicate. In case, the data has been already loaded it will give me a warning advice.
#I have done the same for the second table 
        connection.commit()
        for dat in range (1, len(Locusfile)):
            row = Locusfile [dat].split('\t')
            namelocus = row [0]
            namegene = row  [1]
            nameproteinlength = row [2]
           
            
            tablevariables_LocusGene = (namelocus,namegene, nameproteinlength)
            sql = "INSERT INTO LocusGene(Locus, Gene, ProteinLength) VALUES (%s, %s, %s)"
            try:
                res = cursor.execute(sql,tablevariables_LocusGene)
            except:
                print('Warning, the entry ' + namelocus + ' is already in mysql.')
        connection.commit()    #commit the changes
finally:
    print("Closing connection")
    connection.close()        #close the conection with the database

Warning, the entry AT1G01040 is already in mysql.
Warning, the entry AT1G01060 is already in mysql.
Warning, the entry AT1G01140 is already in mysql.
Warning, the entry AT1G01220 is already in mysql.
Warning, the entry AT2G03720 is already in mysql.
Warning, the entry AT2G03800 is already in mysql.
Warning, the entry AT2G04240 is already in mysql.
Warning, the entry AT2G05210 is already in mysql.
Warning, the entry AT3G02130 is already in mysql.
Warning, the entry AT3G02140 is already in mysql.
Warning, the entry AT3G02230 is already in mysql.
Warning, the entry AT3G02260 is already in mysql.
Warning, the entry AT3G02310 is already in mysql.
Warning, the entry AT3G02680 is already in mysql.
Warning, the entry AT3G02850 is already in mysql.
Warning, the entry AT3G02870 is already in mysql.
Warning, the entry AT3G03260 is already in mysql.
Warning, the entry AT4G14790 is already in mysql.
Warning, the entry AT4G15210 is already in mysql.
Warning, the entry AT4G15560 is already in mysql.
Warning, the entry AT4G15570 is already in mysql.
Warning, the entry AT4G15802 is already in mysql.
Warning, the entry AT4G15880 is already in mysql.
Warning, the entry AT4G16420 is already in mysql.
Warning, the entry AT4G16480 is already in mysql.
Warning, the entry AT5G10480 is already in mysql.
Warning, the entry AT5G10510 is already in mysql.
Warning, the entry AT5G11110 is already in mysql.
Warning, the entry AT5G11260 is already in mysql.
Warning, the entry AT5G11510 is already in mysql.
Warning, the entry AT5G12200 is already in mysql.
Warning, the entry AT5G13290 is already in mysql.
Warning, the entry AT1G01040 is already in mysql.
Warning, the entry AT1G01060 is already in mysql.
Warning, the entry AT1G01140 is already in mysql.
Warning, the entry AT1G01220 is already in mysql.
Warning, the entry AT2G03720 is already in mysql.
Warning, the entry AT2G03800 is already in mysql.
Warning, the entry AT2G04240 is already in mysql.
Warning, the entry AT2G05210 is already in mysql.
Warning, the entry AT3G02130 is already in mysql.
Warning, the entry AT3G02140 is already in mysql.
Warning, the entry AT3G02230 is already in mysql.
Warning, the entry AT3G02260 is already in mysql.
Warning, the entry AT3G02310 is already in mysql.
Warning, the entry AT3G02680 is already in mysql.
Warning, the entry AT3G02850 is already in mysql.
Warning, the entry AT3G02870 is already in mysql.
Warning, the entry AT3G03260 is already in mysql.
Warning, the entry AT4G14790 is already in mysql.
Warning, the entry AT4G15210 is already in mysql.
Warning, the entry AT4G15560 is already in mysql.
Warning, the entry AT4G15570 is already in mysql.
Warning, the entry AT4G15802 is already in mysql.
Warning, the entry AT4G15880 is already in mysql.
Warning, the entry AT4G16420 is already in mysql.
Warning, the entry AT4G16480 is already in mysql.
Warning, the entry AT5G10480 is already in mysql.
Warning, the entry AT5G10510 is already in mysql.
Warning, the entry AT5G11110 is already in mysql.
Warning, the entry AT5G11260 is already in mysql.
Warning, the entry AT5G11510 is already in mysql.
Warning, the entry AT5G12200 is already in mysql.
Warning, the entry AT5G13290 is already in mysql.
Closing connection

In [24]:
%sql SELECT * FROM Germplasm
%sql SELECT * FROM LocusGene

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
32 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
32 rows affected.

[('AT1G01040', 'DCL1', 332),
 ('AT1G01060', 'LHY', 290),
 ('AT1G01140', 'CIPK9', 223),
 ('AT1G01220', 'FKGP', 190),
 ('AT2G03720', 'MRH6', 189),
 ('AT2G03800', 'GEK1', 196),
 ('AT2G04240', 'XERICO', 256),
 ('AT2G05210', 'POT1A', 221),
 ('AT3G02130', 'RPK2', 284),
 ('AT3G02140', 'TMAC2', 300),
 ('AT3G02230', 'RGP1', 301),
 ('AT3G02260', 'BIG', 279),
 ('AT3G02310', 'SEP2', 175),
 ('AT3G02680', 'NBS1', 190),
 ('AT3G02850', 'SKOR', 234),
 ('AT3G02870', 'VTC4', 311),
 ('AT3G03260', 'HDG8', 194),
 ('AT4G14790', 'SUV3', 312),
 ('AT4G15210', 'BAM5', 313),
 ('AT4G15560', 'DXS', 219),
 ('AT4G15570', 'MAA3', 294),
 ('AT4G15802', 'HSBP', 254),
 ('AT4G15880', 'ESD4', 265),
 ('AT4G16420', 'ADA2B', 279),
 ('AT4G16480', 'INT4', 284),
 ('AT5G10480', 'PAS2', 301),
 ('AT5G10510', 'AIL6', 310),
 ('AT5G11110', 'SPS2', 232),
 ('AT5G11260', 'HY5', 221),
 ('AT5G11510', 'MYB3R-4', 336),
 ('AT5G12200', 'PYD2', 310),
 ('AT5G13290', 'CRN', 189)]

Problem 4: 1) the full join 2) Create a joined report that only includes the Genes SKOR and MAA3 3) Create a report that counts the number of entries for each Chromosome (AT1Gxxxxxx to AT5Gxxxxxxx) 4)Create a report that shows the average protein length for the genes on each Chromosome (AT1Gxxxxxx to AT5Gxxxxxxx)

In [242]:
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='root',
                             db='Exam2db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

report = open("report1.txt", "w") # open report for write
try:
    with connection.cursor() as cursor:
        report.write('Locus\tGermplasm\tPhenotype\tPubmed\tLocusgene\tGene\tProteinlength\n') 
        sql = "SELECT * FROM Germplasm INNER JOIN LocusGene ON Germplasm.Locus = LocusGene.Locus" 
        cursor.execute(sql)
        results = cursor.fetchall() 
        for result in results:
            for data in result.values():
                report.write(str(data)) 
                report.write('\t')   
            report.write('\n')
            connection.commit()
        
        checkcontent = open("report1.txt", "r")   #open only to read the file
        print(checkcontent.read())  # print the content of the file 
        report.close()
        checkcontent.close()
        
finally:
    print("")
    connection.close()

Problem 4.2: solution

In [244]:
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='root',
                             db='Exam2db',
                             charset='utf8mb4',  
                             cursorclass=pymysql.cursors.DictCursor)
connection.autocommit = False
report= open("report1.txt", "a") 
try:
    with connection.cursor() as cursor:
            sql = """SELECT Germplasm.Locus,Germplasm.Germplasm,Germplasm.Phenotype,Germplasm.Pubmed,LocusGene.Locus,
            LocusGene.Gene,LocusGene.Proteinlength from Germplasm INNER JOIN LocusGene ON Germplasm.Locus = LocusGene.Locus WHERE Gene LIKE 'SKOR' OR Gene LIKE 'MAA3';"""
            cursor.execute(sql)   # select data from a database
            results = cursor.fetchall()  
            #print(results)
            for result in results: 
                report.write("Solution problem 4.2 report of the Genes SKOR and MAA3:\n") # The first loop read all the data of the sentence selected with the sql
                for data in result.values():     #The second loop read the values
                    report.write(str(data))      #write the data
                    report.write(' ')
                report.write('\n')   #write a new line
            checkcontent = open("report1.txt", "r")   #open only to read the file
            print(checkcontent.read())  # print the content of the file 
            report.close()    #close the report and make the commit
            checkcontent.close()
            connection.commit()
            
finally:
    print("")
    connection.close()    #close the conenction

Locus	Germplasm	Phenotype	Pubmed	Locusgene	Gene	Proteinlength
AT1G01040	CS3828	Increased abundance of miRNA precursors.	17369351	AT1G01040	DCL1	332
AT1G01060	lhy-101	The mutant plants are hypersensitive to both FRc and Rc light treatments in hypocotyl elongation and exhibits a small reciprocal enlargement in cotyledon area, albeit not statistically significant.	16891401	AT1G01060	LHY	290
AT1G01140	SALK_058629	hypersensitive to low potassium media	17486125	AT1G01140	CIPK9	223
AT1G01220	SALK_012400C	fkgp-1 mutants have about 40 times more L-fucose than wild type Arabidopsis plants, but the levels of other monosaccharides do not appear to differ significantly in the mutants. No obvious phenotypic abnormalities were observed in the fkgp-1 mutants, nor were any differences in the sugar composition of cell wall polysaccharides detected.	18199744	AT1G01220	FKGP	190
AT2G03720	SALK_042433	Multiple straight hairs	16367956	AT2G03720	MRH6	189
AT2G03800	gek1-1	Ethanol hypersensitivity.	15215505	AT2G03800	GEK1	196
AT2G04240	xerico	Resistant to exogenous ABA. Seeds contained lower amounts of endogenous ABA than wildtype.	17933900	AT2G04240	XERICO	256
AT2G05210	pot1-1	No visible phenotype.	17627276	AT2G05210	POT1A	221
AT3G02130	rpk2-2	The homozygous progeny is indistinguishable from wild-type plants during vegetative growth but showed several morphological alterations after bolting. These plants displayed enhanced inflorescence branching and formed three times as many siliques and flowers as did wild-type plants.	17419837	AT3G02130	RPK2	284
AT3G02140	afp4-1	Decreased germination on high concentrations of glucose and sorbitol.	18484180	AT3G02140	TMAC2	300
AT3G02230	rgp1-1	rgp1-1 mutants have significantly lower levels of UDP-L-arabinose mutase activity compared to wild-type plants and significantly lower levels of arabinose in their cell walls.	21478444	AT3G02230	RGP1	301
AT3G02260	tir3-1 RGLG1:rglg1 rglg2	The triple homozygous progeny has low viability, accumulated anthocyanin, and all plants died before shoot emergence.	17586653	AT3G02260	BIG	279
AT3G02310	sep2-1	Non-described subtle phenotype.	10821278	AT3G02310	SEP2	175
AT3G02680	atnbs1-1	Significantly smaller when grown in the presence of methyl methanosulfonate (MMS) with root growth.  Normal growth under standard growth conditions.	17672843	AT3G02680	NBS1	190
AT3G02850	CS3816	The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion.	17568770	AT3G02850	SKOR	234
AT3G02870	vtc4-1	ascorbate deficient	16595667	AT3G02870	VTC4	311
AT3G03260	hdg8-1	No visible phenotype.	16778018	AT3G03260	HDG8	194
AT4G14790	pdd17	Defective pollen development.	19237690	AT4G14790	SUV3	312
AT4G15210	bmy1-2	Plants cold-shocked for 6h have an increased starch content compared to wildtype.	16297066	AT4G15210	BAM5	313
AT4G15560	cla1-1	Mutant seeds grown on medium supplemented with non-phosphorylated synthetic 1-deoxy-D-xylulose (DX) develop green leaves.	10982425	AT4G15560	DXS	219
AT4G15570	maa3	Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT.	18772186	AT4G15570	MAA3	294
AT4G15802	Athspb-2	Early flowering, reduced fertility, aborted seeds.	20388662	AT4G15802	HSBP	254
AT4G15880	esd4-2	Decreased mRNA levels of the floral repressors FLC and MAF4 and increased mRNA levels of the floral activators FT and SOC1.	17513499	AT4G15880	ESD4	265
AT4G16420	prz1-1	Altered response to auxin and cytokinin	12747832	AT4G16420	ADA2B	279
AT4G16480	atint4-2	No visible phenotype.	16603666	AT4G16480	INT4	284
AT5G10480	pas2-3	Segregates 25% embryo lethal.	18799749	AT5G10480	PAS2	301
AT5G10510	plt3-1	Short roots and shortened root meristem.	17960244	AT5G10510	AIL6	310
AT5G11110	kns2	Defects are specific to pollen exine structure. Smaller mesh size in the exine structure. Increased number of baculae. Fully fertile.	18779216	AT5G11110	SPS2	232
AT5G11260	hy5-101	Under FRc conditions, the length mutant hypocotyls is increased compared to that of wild-type plants.  Under Rc conditions, the hypocotyl length is also increased and the cotyledon area is smaller.	16891401	AT5G11260	HY5	221
AT5G11510	myb3r4-1	No visible phenotype.	17287251	AT5G11510	MYB3R-4	336
AT5G12200	pyd2-2	The pyd2-2 mutant has a wild-type appearance under normal growth conditions. Pyrimidine nucleotide and uridine levels are not changed in the mutant, but uracil levels are increased. These mutants cannot grow normally when uracil is provided as a sole nitrogen source.	19413687	AT5G12200	PYD2	310
AT5G13290	crn-1	Increased meristem size. Vegetative meristems are are 30% larger than wild type. After bolting inflorescence meristems are enlarged and occasionally fasciated. Flowers occasionally produce extra organs in the first 3.	12345678	AT5G13290	CRN	189
 Report of the Genes SKOR and MAA3:
AT3G02850 CS3816 The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion. 17568770 AT3G02850 SKOR 234
 Report of the Genes SKOR and MAA3:
AT4G15570 maa3 Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT. 18772186 AT4G15570 MAA3 294

In [245]:
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='root',
                             db='Exam2db',
                             charset='utf8mb4',  
                             cursorclass=pymysql.cursors.DictCursor)
connection.autocommit = False
#I use the command SELECT COUNT (*) to find a specific sequence inside AT1G/AT2G/AT3G/AT4G/AT5G. I am doing the same for all of them
try:
    with connection.cursor() as cursor:
            sql1 = """SELECT COUNT(*) FROM Germplasm RIGHT JOIN LocusGene ON Germplasm.Locus = LocusGene.Locus WHERE Germplasm.Locus LIKE 'AT1G%';"""
            cursor.execute(sql1)
            results1 = cursor.fetchall()
            report= open("report1.txt", "a")  #open the fil for append to do not overwrite
            report.write ("Number of entries Chromosome 1" + str(results1) + "\n")
      
            sql2 = """SELECT COUNT(*) FROM Germplasm INNER JOIN LocusGene ON Germplasm.Locus = LocusGene.Locus WHERE Germplasm.Locus LIKE 'AT2G%';"""
            cursor.execute(sql2)
            results2 = cursor.fetchall()
            report.write("Number of entries Chromosome 2" + str(results2)+ "\n")
            
            sql3 = """SELECT COUNT(*) FROM Germplasm INNER JOIN LocusGene ON Germplasm.Locus = LocusGene.Locus WHERE Germplasm.Locus LIKE 'AT3G%';"""
            cursor.execute(sql3)
            results3 = cursor.fetchall()
            report.write("Number of entries Chromosome 3 " + str(results3) + "\n")
            
            sql4 = """SELECT COUNT(*) FROM Germplasm INNER JOIN LocusGene ON Germplasm.Locus = LocusGene.Locus WHERE Germplasm.Locus LIKE 'AT4G%';"""
            cursor.execute(sql4)
            results4 = cursor.fetchall()
            report.write("Number of entries Chromosome 4 " + str(results4) + "\n")
            
            sql5 = """SELECT COUNT(*) FROM Germplasm INNER JOIN LocusGene ON Germplasm.Locus = LocusGene.Locus WHERE Germplasm.Locus LIKE 'AT2G%';"""
            cursor.execute(sql5)
            results5 = cursor.fetchall()
            report.write("Number of entries Chromosome 5" + str(results5) + "\n")
            
            
            report.close()
            checkcontent = open("report1.txt", "r")  # I open the file to read and do not modify anything
            print(checkcontent.read())  
            connection.commit()   # commit
    
finally:
    print("")
    connection.close()    # close conneciton

Locus	Germplasm	Phenotype	Pubmed	Locusgene	Gene	Proteinlength
AT1G01040	CS3828	Increased abundance of miRNA precursors.	17369351	AT1G01040	DCL1	332
AT1G01060	lhy-101	The mutant plants are hypersensitive to both FRc and Rc light treatments in hypocotyl elongation and exhibits a small reciprocal enlargement in cotyledon area, albeit not statistically significant.	16891401	AT1G01060	LHY	290
AT1G01140	SALK_058629	hypersensitive to low potassium media	17486125	AT1G01140	CIPK9	223
AT1G01220	SALK_012400C	fkgp-1 mutants have about 40 times more L-fucose than wild type Arabidopsis plants, but the levels of other monosaccharides do not appear to differ significantly in the mutants. No obvious phenotypic abnormalities were observed in the fkgp-1 mutants, nor were any differences in the sugar composition of cell wall polysaccharides detected.	18199744	AT1G01220	FKGP	190
AT2G03720	SALK_042433	Multiple straight hairs	16367956	AT2G03720	MRH6	189
AT2G03800	gek1-1	Ethanol hypersensitivity.	15215505	AT2G03800	GEK1	196
AT2G04240	xerico	Resistant to exogenous ABA. Seeds contained lower amounts of endogenous ABA than wildtype.	17933900	AT2G04240	XERICO	256
AT2G05210	pot1-1	No visible phenotype.	17627276	AT2G05210	POT1A	221
AT3G02130	rpk2-2	The homozygous progeny is indistinguishable from wild-type plants during vegetative growth but showed several morphological alterations after bolting. These plants displayed enhanced inflorescence branching and formed three times as many siliques and flowers as did wild-type plants.	17419837	AT3G02130	RPK2	284
AT3G02140	afp4-1	Decreased germination on high concentrations of glucose and sorbitol.	18484180	AT3G02140	TMAC2	300
AT3G02230	rgp1-1	rgp1-1 mutants have significantly lower levels of UDP-L-arabinose mutase activity compared to wild-type plants and significantly lower levels of arabinose in their cell walls.	21478444	AT3G02230	RGP1	301
AT3G02260	tir3-1 RGLG1:rglg1 rglg2	The triple homozygous progeny has low viability, accumulated anthocyanin, and all plants died before shoot emergence.	17586653	AT3G02260	BIG	279
AT3G02310	sep2-1	Non-described subtle phenotype.	10821278	AT3G02310	SEP2	175
AT3G02680	atnbs1-1	Significantly smaller when grown in the presence of methyl methanosulfonate (MMS) with root growth.  Normal growth under standard growth conditions.	17672843	AT3G02680	NBS1	190
AT3G02850	CS3816	The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion.	17568770	AT3G02850	SKOR	234
AT3G02870	vtc4-1	ascorbate deficient	16595667	AT3G02870	VTC4	311
AT3G03260	hdg8-1	No visible phenotype.	16778018	AT3G03260	HDG8	194
AT4G14790	pdd17	Defective pollen development.	19237690	AT4G14790	SUV3	312
AT4G15210	bmy1-2	Plants cold-shocked for 6h have an increased starch content compared to wildtype.	16297066	AT4G15210	BAM5	313
AT4G15560	cla1-1	Mutant seeds grown on medium supplemented with non-phosphorylated synthetic 1-deoxy-D-xylulose (DX) develop green leaves.	10982425	AT4G15560	DXS	219
AT4G15570	maa3	Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT.	18772186	AT4G15570	MAA3	294
AT4G15802	Athspb-2	Early flowering, reduced fertility, aborted seeds.	20388662	AT4G15802	HSBP	254
AT4G15880	esd4-2	Decreased mRNA levels of the floral repressors FLC and MAF4 and increased mRNA levels of the floral activators FT and SOC1.	17513499	AT4G15880	ESD4	265
AT4G16420	prz1-1	Altered response to auxin and cytokinin	12747832	AT4G16420	ADA2B	279
AT4G16480	atint4-2	No visible phenotype.	16603666	AT4G16480	INT4	284
AT5G10480	pas2-3	Segregates 25% embryo lethal.	18799749	AT5G10480	PAS2	301
AT5G10510	plt3-1	Short roots and shortened root meristem.	17960244	AT5G10510	AIL6	310
AT5G11110	kns2	Defects are specific to pollen exine structure. Smaller mesh size in the exine structure. Increased number of baculae. Fully fertile.	18779216	AT5G11110	SPS2	232
AT5G11260	hy5-101	Under FRc conditions, the length mutant hypocotyls is increased compared to that of wild-type plants.  Under Rc conditions, the hypocotyl length is also increased and the cotyledon area is smaller.	16891401	AT5G11260	HY5	221
AT5G11510	myb3r4-1	No visible phenotype.	17287251	AT5G11510	MYB3R-4	336
AT5G12200	pyd2-2	The pyd2-2 mutant has a wild-type appearance under normal growth conditions. Pyrimidine nucleotide and uridine levels are not changed in the mutant, but uracil levels are increased. These mutants cannot grow normally when uracil is provided as a sole nitrogen source.	19413687	AT5G12200	PYD2	310
AT5G13290	crn-1	Increased meristem size. Vegetative meristems are are 30% larger than wild type. After bolting inflorescence meristems are enlarged and occasionally fasciated. Flowers occasionally produce extra organs in the first 3.	12345678	AT5G13290	CRN	189
 Report of the Genes SKOR and MAA3:
AT3G02850 CS3816 The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion. 17568770 AT3G02850 SKOR 234
 Report of the Genes SKOR and MAA3:
AT4G15570 maa3 Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT. 18772186 AT4G15570 MAA3 294
 Report of the Genes SKOR and MAA3:
AT3G02850 CS3816 The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion. 17568770 AT3G02850 SKOR 234
 Report of the Genes SKOR and MAA3:
AT4G15570 maa3 Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT. 18772186 AT4G15570 MAA3 294
Number of entries Chromosome 1[{'COUNT(*)': 4}]
Number of entries Chromosome 2[{'COUNT(*)': 4}]
Number of entries Chromosome 3 [{'COUNT(*)': 9}]
Number of entries Chromosome 4 [{'COUNT(*)': 8}]
Number of entries Chromosome 5[{'COUNT(*)': 4}]

Problem 4.4: In this case I open the connection, and I a using the SELECT AVG function to find in the INNER Join of both tables (Germplasm and LocusGene) the average lenght of proteinLenght in entries that correspond to Locus ATG1,ATG2 ,ATG3 ,ATG4  and ATG5 . All the information is wrote using the "Append" to do not overwrite the information.  We will get the length in decimals, since the average is a floating point type of data.

In [247]:
connection = pymysql.connect(host='localhost',       #Open the conecction with the terminal 
                             user='root',
                             password='root',
                             db='Exam2db',
                             charset='utf8mb4',  
                             cursorclass=pymysql.cursors.DictCursor)
connection.autocommit = False        # The changes are temporals until I commit 

# I use the command Selection Average to calculate the  Protein lenght of the INNER join of tboth tables for the structure ATG1,2,3,4 and 5.
try:
    with connection.cursor() as cursor:     
            
            sql1 = """SELECT AVG(ProteinLength) FROM LocusGene INNER JOIN Germplasm ON LocusGene.Locus = Germplasm.Locus  WHERE LocusGene.Locus LIKE 'AT1G%';"""
            cursor.execute(sql1)   #I use the command SELECT AVR (the column)
            results1 = cursor.fetchall()
            report= open("report1.txt", "a")     #Open the Report file for append and put the pointer at the END of the file 
            report.write("Average ProteinLength in the Chromosome 1 is: " + str(results1)+"\n") #print the results as a string
            
            sql2 = """SELECT AVG(ProteinLength) FROM LocusGene INNER JOIN Germplasm ON LocusGene.Locus = Germplasm.Locus  WHERE LocusGene.Locus LIKE 'AT2G%';"""
            cursor.execute(sql2) 
            results2 = cursor.fetchall()
            report.write("Average  ProteinLength in the Chromosome 2 is: " + str(results2)+"\n") 
            
            sql3 = """SELECT AVG(ProteinLength) FROM LocusGene INNER JOIN Germplasm ON LocusGene.Locus = Germplasm.Locus  WHERE LocusGene.Locus LIKE 'AT3G%';"""
            cursor.execute(sql3) 
            results3 = cursor.fetchall()
            report.write("Average ProteinLength in the Chromosome 3 is: " + str(results3)+"\n") 
            
            sql4 = """SELECT AVG(ProteinLength) FROM LocusGene INNER JOIN Germplasm ON LocusGene.Locus = Germplasm.Locus  WHERE LocusGene.Locus LIKE 'AT4G%';"""
            cursor.execute(sql4) 
            results4 = cursor.fetchall()
            report.write("Average ProteinLength in the Chromosome 4 is: " + str(results4)+"\n") 
            
            sql5 = """SELECT AVG(ProteinLength) FROM LocusGene INNER JOIN Germplasm ON LocusGene.Locus = Germplasm.Locus  WHERE LocusGene.Locus LIKE 'AT5G%';"""
            cursor.execute(sql5) 
            results5 = cursor.fetchall()
            report.write("Average ProteinLength in the Chromosome 5 is: " + str(results5)+"\n") 
            
            Report.close() # Close the file 
            checkcontent = open("report1.txt", "r")  # I open the file to read and do not modify anything
            print(checkcontent.read())  
            connection.commit()    #Commit the changes 
    
finally:
    print("")
    connection.close()    # Close the conecction

Locus	Germplasm	Phenotype	Pubmed	Locusgene	Gene	Proteinlength
AT1G01040	CS3828	Increased abundance of miRNA precursors.	17369351	AT1G01040	DCL1	332
AT1G01060	lhy-101	The mutant plants are hypersensitive to both FRc and Rc light treatments in hypocotyl elongation and exhibits a small reciprocal enlargement in cotyledon area, albeit not statistically significant.	16891401	AT1G01060	LHY	290
AT1G01140	SALK_058629	hypersensitive to low potassium media	17486125	AT1G01140	CIPK9	223
AT1G01220	SALK_012400C	fkgp-1 mutants have about 40 times more L-fucose than wild type Arabidopsis plants, but the levels of other monosaccharides do not appear to differ significantly in the mutants. No obvious phenotypic abnormalities were observed in the fkgp-1 mutants, nor were any differences in the sugar composition of cell wall polysaccharides detected.	18199744	AT1G01220	FKGP	190
AT2G03720	SALK_042433	Multiple straight hairs	16367956	AT2G03720	MRH6	189
AT2G03800	gek1-1	Ethanol hypersensitivity.	15215505	AT2G03800	GEK1	196
AT2G04240	xerico	Resistant to exogenous ABA. Seeds contained lower amounts of endogenous ABA than wildtype.	17933900	AT2G04240	XERICO	256
AT2G05210	pot1-1	No visible phenotype.	17627276	AT2G05210	POT1A	221
AT3G02130	rpk2-2	The homozygous progeny is indistinguishable from wild-type plants during vegetative growth but showed several morphological alterations after bolting. These plants displayed enhanced inflorescence branching and formed three times as many siliques and flowers as did wild-type plants.	17419837	AT3G02130	RPK2	284
AT3G02140	afp4-1	Decreased germination on high concentrations of glucose and sorbitol.	18484180	AT3G02140	TMAC2	300
AT3G02230	rgp1-1	rgp1-1 mutants have significantly lower levels of UDP-L-arabinose mutase activity compared to wild-type plants and significantly lower levels of arabinose in their cell walls.	21478444	AT3G02230	RGP1	301
AT3G02260	tir3-1 RGLG1:rglg1 rglg2	The triple homozygous progeny has low viability, accumulated anthocyanin, and all plants died before shoot emergence.	17586653	AT3G02260	BIG	279
AT3G02310	sep2-1	Non-described subtle phenotype.	10821278	AT3G02310	SEP2	175
AT3G02680	atnbs1-1	Significantly smaller when grown in the presence of methyl methanosulfonate (MMS) with root growth.  Normal growth under standard growth conditions.	17672843	AT3G02680	NBS1	190
AT3G02850	CS3816	The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion.	17568770	AT3G02850	SKOR	234
AT3G02870	vtc4-1	ascorbate deficient	16595667	AT3G02870	VTC4	311
AT3G03260	hdg8-1	No visible phenotype.	16778018	AT3G03260	HDG8	194
AT4G14790	pdd17	Defective pollen development.	19237690	AT4G14790	SUV3	312
AT4G15210	bmy1-2	Plants cold-shocked for 6h have an increased starch content compared to wildtype.	16297066	AT4G15210	BAM5	313
AT4G15560	cla1-1	Mutant seeds grown on medium supplemented with non-phosphorylated synthetic 1-deoxy-D-xylulose (DX) develop green leaves.	10982425	AT4G15560	DXS	219
AT4G15570	maa3	Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT.	18772186	AT4G15570	MAA3	294
AT4G15802	Athspb-2	Early flowering, reduced fertility, aborted seeds.	20388662	AT4G15802	HSBP	254
AT4G15880	esd4-2	Decreased mRNA levels of the floral repressors FLC and MAF4 and increased mRNA levels of the floral activators FT and SOC1.	17513499	AT4G15880	ESD4	265
AT4G16420	prz1-1	Altered response to auxin and cytokinin	12747832	AT4G16420	ADA2B	279
AT4G16480	atint4-2	No visible phenotype.	16603666	AT4G16480	INT4	284
AT5G10480	pas2-3	Segregates 25% embryo lethal.	18799749	AT5G10480	PAS2	301
AT5G10510	plt3-1	Short roots and shortened root meristem.	17960244	AT5G10510	AIL6	310
AT5G11110	kns2	Defects are specific to pollen exine structure. Smaller mesh size in the exine structure. Increased number of baculae. Fully fertile.	18779216	AT5G11110	SPS2	232
AT5G11260	hy5-101	Under FRc conditions, the length mutant hypocotyls is increased compared to that of wild-type plants.  Under Rc conditions, the hypocotyl length is also increased and the cotyledon area is smaller.	16891401	AT5G11260	HY5	221
AT5G11510	myb3r4-1	No visible phenotype.	17287251	AT5G11510	MYB3R-4	336
AT5G12200	pyd2-2	The pyd2-2 mutant has a wild-type appearance under normal growth conditions. Pyrimidine nucleotide and uridine levels are not changed in the mutant, but uracil levels are increased. These mutants cannot grow normally when uracil is provided as a sole nitrogen source.	19413687	AT5G12200	PYD2	310
AT5G13290	crn-1	Increased meristem size. Vegetative meristems are are 30% larger than wild type. After bolting inflorescence meristems are enlarged and occasionally fasciated. Flowers occasionally produce extra organs in the first 3.	12345678	AT5G13290	CRN	189
 Report of the Genes SKOR and MAA3:
AT3G02850 CS3816 The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion. 17568770 AT3G02850 SKOR 234
 Report of the Genes SKOR and MAA3:
AT4G15570 maa3 Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT. 18772186 AT4G15570 MAA3 294
 Report of the Genes SKOR and MAA3:
AT3G02850 CS3816 The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion. 17568770 AT3G02850 SKOR 234
 Report of the Genes SKOR and MAA3:
AT4G15570 maa3 Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT. 18772186 AT4G15570 MAA3 294
Number of entries Chromosome 1[{'COUNT(*)': 4}]
Number of entries Chromosome 2[{'COUNT(*)': 4}]
Number of entries Chromosome 3 [{'COUNT(*)': 9}]
Number of entries Chromosome 4 [{'COUNT(*)': 8}]
Number of entries Chromosome 5[{'COUNT(*)': 4}]
Average ProteinLength in the Chromosome 1 is: [{'AVG(ProteinLength)': Decimal('258.7500')}]
Average  ProteinLength in the Chromosome 2 is: [{'AVG(ProteinLength)': Decimal('215.5000')}]
Average ProteinLength in the Chromosome 3 is: [{'AVG(ProteinLength)': Decimal('252.0000')}]
Average ProteinLength in the Chromosome 4 is: [{'AVG(ProteinLength)': Decimal('277.5000')}]
Average ProteinLength in the Chromosome 5 is: [{'AVG(ProteinLength)': Decimal('271.2857')}]